name: Publish

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  read-version:
    name: Read Version
    uses: ./.github/workflows/read-version.yml

  build:
    name: Build
    needs: [read-version]
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: ${{ needs.read-version.outputs.version }}

  publish:
    name: Publish
    runs-on: ubuntu-latest

    needs: [build, read-version]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.read-version.outputs.version }}
          path: build/

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: npm Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
